# Generated by Django 3.0.6 on 2020-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsBaliraja', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryName', models.CharField(max_length=100, unique=True)),
                ('catagoryImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
