# Generated by Django 3.0.6 on 2020-05-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsBaliraja', '0004_categories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='aimsBaliraja_categories',
        ),
    ]
