# Generated by Django 3.0.6 on 2020-05-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsBaliraja', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mob_no',
        ),
    ]
